<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'IDG_PRODUCTS_POST_TYPE_JS', 'post_type-2e066448.js' );
define( 'IDG_PRODUCTS_PRODUCTS_JS', 'products-2e066448.js' );
define( 'IDG_PRODUCTS_POST_TYPE_CSS', 'post_type.css' );
define( 'IDG_PRODUCTS_PRODUCTS_CSS', 'products.css' );

