<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'IDG_GOLDEN_TAXONOMY_METABOXES_JS', 'metaboxes-f673c716.js' );
define( 'IDG_GOLDEN_TAXONOMY_METABOXES_CSS', 'metaboxes.css' );

