<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'IDG_CONFIGURATION_ADMIN_JS', 'admin-3c25702c.js' );
define( 'IDG_CONFIGURATION_ADMIN_CSS', 'admin.css' );

