<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'IDG_BASE_THEME_ADMIN_JS', 'admin-900b44b1.js' );
define( 'IDG_BASE_THEME_AJAXLOAD_POSTS_JS', 'ajaxload-posts-900b44b1.js' );
define( 'IDG_BASE_THEME_AMP_JS', 'amp-900b44b1.js' );
define( 'IDG_BASE_THEME_BUNDLE_JS', 'bundle-900b44b1.js' );
define( 'IDG_BASE_THEME_GUTENBERG_JS', 'gutenberg-900b44b1.js' );
define( 'IDG_BASE_THEME_PACKAGES_JS', 'packages-900b44b1.js' );
define( 'IDG_BASE_THEME_SHARED_JS', 'shared-900b44b1.js' );
define( 'IDG_BASE_THEME_ADMIN_CSS', 'admin.css' );
define( 'IDG_BASE_THEME_AMP_CSS', 'amp.css' );
define( 'IDG_BASE_THEME_BUNDLE_CSS', 'bundle.css' );
define( 'IDG_BASE_THEME_GUTENBERG_CSS', 'gutenberg.css' );
define( 'IDG_BASE_THEME_SHARED_CSS', 'shared.css' );

