<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'MULTI_TITLE_INDEX_JS', 'index-70135139.js' );
define( 'MULTI_TITLE_INDEX_CSS', 'index.css' );

