<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'IDG_PUBLISHING_FLOW_ADMIN_JS', 'admin-196d812f.js' );
define( 'IDG_PUBLISHING_FLOW_PUBLICATION_TAXONOMY_JS', 'publication-taxonomy-196d812f.js' );
define( 'IDG_PUBLISHING_FLOW_ADMIN_CSS', 'admin.css' );
define( 'IDG_PUBLISHING_FLOW_PUBLICATION_TAXONOMY_CSS', 'publication-taxonomy.css' );

