<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'IDG_ASSET_MANAGER_ADMIN_JS', 'admin-7c493de7.js' );
define( 'IDG_ASSET_MANAGER_GUTENBERG_JS', 'gutenberg-7c493de7.js' );
define( 'IDG_ASSET_MANAGER_ADMIN_CSS', 'admin.css' );
define( 'IDG_ASSET_MANAGER_GUTENBERG_CSS', 'gutenberg.css' );

