<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'IDG_SPONSORED_LINKS_ADMIN_JS', 'admin-84217432.js' );
define( 'IDG_SPONSORED_LINKS_DUMMY_JS', 'dummy-84217432.js' );
define( 'IDG_SPONSORED_LINKS_DUMMY_CSS', 'dummy.css' );

