<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'IDG_POST_TYPE_FILTERS_ADMIN_JS', 'admin-b25ed470.js' );
define( 'IDG_POST_TYPE_FILTERS_ADMIN_CSS', 'admin.css' );

