<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'IDG_TERRITORIES_EDIT_TERRITORY_JS', 'edit-territory-812fee62.js' );
define( 'IDG_TERRITORIES_EDIT_TERRITORY_CSS', 'edit-territory.css' );

