<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'CUSTOM_FIELDS_ADMIN_JS', 'admin-3dde70c6.js' );
define( 'CUSTOM_FIELDS_ADMIN_CSS', 'admin.css' );

