import mobileNav from './modules/navigation-mobile';
import priorityNav from './modules/navigation-priority';
import dropdownNav from './modules/navigation-dropdown';
import overlaySite from './modules/site-overlay';
import toggleTooltip from './modules/tooltip-toggle';
import tabNavigation from './modules/tab-navigation';
import siteSearch from './modules/site-search';
import accessibility from './modules/accessibility';
import tocHeader from './modules/toc-header';
import viewMorePrices from './modules/price-comparison-view-more';
import returnToTop from './modules/return-to-top';
import relatedSites from './modules/related-sites-dropdown';
import legacy from './modules/legacy';
import paginationLimit from './modules/pagination-limit';
import newsletterSignUp from './modules/newsletter-signup';

mobileNav();
priorityNav();
dropdownNav();
overlaySite();
toggleTooltip();
tabNavigation();
siteSearch();
accessibility();
tocHeader();
viewMorePrices();
returnToTop();
relatedSites();
legacy();
paginationLimit();
newsletterSignUp();
