<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'IDG_THIRD_PARTY_ADMIN_JS', 'admin-a45762d1.js' );
define( 'IDG_THIRD_PARTY_INDEX_JS', 'index-a45762d1.js' );
define( 'IDG_THIRD_PARTY_PREBID_ADS_JS', 'prebid-ads-a45762d1.js' );
define( 'IDG_THIRD_PARTY_INDEX_CSS', 'index.css' );

