<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'MACWORLD_COM_CHILD_THEME_DUMMY_JS', 'dummy-7ad2e40f.js' );
define( 'MACWORLD_COM_CHILD_THEME_THEME_JS', 'theme-7ad2e40f.js' );
define( 'MACWORLD_COM_CHILD_THEME_DUMMY_CSS', 'dummy.css' );
define( 'MACWORLD_COM_CHILD_THEME_THEME_CSS', 'theme.css' );

