<?php
/**
 * @file - Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'CIO_CHILD_THEME_DUMMY_JS', 'dummy-2d479215.js' );
define( 'CIO_CHILD_THEME_DUMMY_CSS', 'dummy.css' );

